In [1]:
import io
import pandas as pd

In [2]:
!pip install ipython-autotime

Looking in indexes: http://jetson.webredirect.org/jp6/cu122


In [3]:
%load_ext autotime

time: 262 μs (started: 2025-07-08 06:34:49 +00:00)


In [7]:
sample_df = pd.read_csv('dataset/iris.csv', header=0)

time: 7.43 ms (started: 2025-07-08 06:50:30 +00:00)


In [8]:
sample_df.head()

F1   F2   F3   F4        Label
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

time: 50.2 ms (started: 2025-07-08 06:50:57 +00:00)


In [12]:
import torch #used for deep learning and tensor computation
from sklearn.preprocessing import LabelEncoder
import torch.nn.functional as F
dataset = sample_df.values
X = dataset[:,0:4].astype(float)#input smpi column 4...outcome column 9 adalah output yg nilainya 1 atau 0
Y = ['Setosa', 'Versicolor', 'Virginica'] 

class_map = {
    'Setosa': [1, 0, 0],
    'Versicolor': [0, 1, 0],
    'Virginica': [0, 0, 1]
}



# Print the NumPy arrays
print("NumPy X:", X)
print("NumPy Y:", Y)

# Step 4: Convert NumPy arrays to PyTorch tensors
X_tensor = torch.tensor(X, dtype=torch.float32)
Y_one_hot = torch.tensor([class_map[label] for label in Y], dtype=torch.float32)


# Print the PyTorch tensors
print("PyTorch X_tensor:", X_tensor)
print("PyTorch Y_tensor:", Y_tensor)

NumPy X: [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6

In [13]:
!pip install scikit-learn -i https://pypi.org/simple #popular machine learning library for python

time: 3.47 s (started: 2025-07-08 07:10:44 +00:00)


In [14]:
!pip install matplotlib

Looking in indexes: http://jetson.webredirect.org/jp6/cu122
time: 3.53 s (started: 2025-07-08 07:11:03 +00:00)


In [27]:
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
from torch.utils.data import Dataset, DataLoader, random_split
from sklearn import datasets
from sklearn.model_selection import train_test_split
import pandas as pd

time: 1.48 ms (started: 2025-07-08 07:31:15 +00:00)


In [19]:
# Define model parameters
input_dim = 4  # Iris dataset has 4 input features
hidden_dim1 = 8  # Number of neurons in the first hidden layer
hidden_dim2 = 6  # Number of neurons in the second hidden layer
output_dim = 3  # 3 classes: Setosa, Versicolor, Virginica
num_epochs = 1000  # Number of epochs for training
batch_size = 16  # Number of samples per batch
learning_rate = 0.001  # Learning rate for training


time: 3.37 ms (started: 2025-07-08 07:19:52 +00:00)


In [28]:
# Load the Iris dataset from sklearn
iris = datasets.load_iris()
data = iris.data  # Features: 4 columns
labels = iris.target  # Labels: 3 classes (Setosa, Versicolor, Virginica)

# Convert the data to a pandas DataFrame for easier handling
df = pd.DataFrame(data, columns=iris.feature_names)
df['Species'] = labels

# Dataset class for Iris dataset
class IrisDataset(Dataset):
    def __init__(self, data):
        # Features (4 columns of data)
        self.features = torch.tensor(data.drop('Species', axis=1).values, dtype=torch.float32)
        # Labels: Iris target labels (0, 1, 2 for Setosa, Versicolor, Virginica)
        self.labels = torch.tensor(data['Species'].values, dtype=torch.long)

    def __len__(self):
        return len(self.features)

    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]

# Split the dataset into training, validation, and test sets
iris_dataset = IrisDataset(df)

# Define the sizes of the splits
total_size = len(iris_dataset)
train_size = int(0.7 * total_size)  # 70% for training
val_size = int(0.1 * total_size)  # 10% for validation
test_size = total_size - train_size - val_size  # Remaining 20% for testing

# Split the dataset into train, validation, and test sets
train_data, temp_data = random_split(iris_dataset, [train_size, val_size + test_size])
val_data, test_data = random_split(temp_data, [val_size, test_size])

# Create DataLoaders
train_loader = DataLoader(train_data, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_data, batch_size=batch_size)
test_loader = DataLoader(test_data, batch_size=batch_size)


time: 22.7 ms (started: 2025-07-08 07:33:19 +00:00)


In [29]:
# Define the neural network model for Iris dataset
class IrisNN(nn.Module):
    def __init__(self, input_dim, hidden_dim1, hidden_dim2, output_dim):
        super(IrisNN, self).__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim1)  # Input layer to hidden layer 1
        self.fc2 = nn.Linear(hidden_dim1, hidden_dim2)  # Hidden layer 1 to hidden layer 2
        self.fc3 = nn.Linear(hidden_dim2, output_dim)  # Hidden layer 2 to output layer
        self.relu = nn.ReLU()
        self.softmax = nn.Softmax(dim=1)  # Softmax activation for multi-class classification

    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.fc3(x)
        x = self.softmax(x)  # Output class probabilities
        return x


time: 5.17 ms (started: 2025-07-08 07:33:43 +00:00)


In [30]:
## Instantiate the model
model = IrisNN(input_dim, hidden_dim1, hidden_dim2, output_dim)

# Define loss function and optimizer
criterion = nn.CrossEntropyLoss()  # Cross-entropy loss for multi-class classification
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

time: 6.14 ms (started: 2025-07-08 07:34:26 +00:00)


In [23]:
# Define the path to save the model
model_path = 'model/pima_model_KV.pt'

time: 779 μs (started: 2025-07-08 07:24:48 +00:00)


In [31]:
# Function to calculate accuracy
def calculate_accuracy(outputs, labels):
    _, predicted = torch.max(outputs, 1)
    correct = (predicted == labels).sum().item()
    accuracy = correct / labels.size(0)
    return accuracy

time: 1.26 ms (started: 2025-07-08 07:35:07 +00:00)


In [47]:
# Initialize lists to store loss and accuracy
epoch_losses = []
epoch_accuracies = []
val_accuracies = []
val_losses = []
best_val_accuracy = 0.0
model_path = "best_model.pth"  # Path to save the best model

# Training loop
model.train()  # Start Training
for epoch in range(num_epochs):
    epoch_loss = 0.0
    epoch_accuracy = 0.0
    for i, (input, labels) in enumerate(train_loader):  # Renamed 'features' to 'input'
        # Forward pass
        outputs = model(input)

        # Compute the loss
        loss = criterion(outputs, labels)

        # Backward pass and optimization
        optimizer.zero_grad()  # Clear previous gradient
        loss.backward()  # Compute gradient from current loss
        optimizer.step()  # Update model parameter

        # Calculate batch accuracy
        accuracy = calculate_accuracy(outputs, labels)

        epoch_loss += loss.item()
        epoch_accuracy += accuracy

    epoch_loss /= len(train_loader)
    epoch_accuracy /= len(train_loader)

    epoch_losses.append(epoch_loss)
    epoch_accuracies.append(epoch_accuracy)

    # Validation
    val_loss = 0.0  # Initialize validation loss variable
    val_accuracy = 0.0
    model.eval()  # Set the model to evaluation mode
    with torch.no_grad():
        for input_val, labels_val in val_loader:
            outputs_val = model(input_val)
            loss_val = criterion(outputs_val, labels_val)  # Compute validation loss
            accuracy_val = calculate_accuracy(outputs_val, labels_val)  # Calculate validation accuracy
            val_loss += loss_val.item()  # Accumulate validation loss
            val_accuracy += accuracy_val
        val_loss /= len(val_loader)  # Compute average validation loss
        val_losses.append(val_loss)  # Store validation loss
        val_accuracy /= len(val_loader)  # Average validation accuracy
        val_accuracies.append(val_accuracy)
    model.train()  # Set the model back to training mode

    # Save model if validation accuracy improves
    if val_accuracy > best_val_accuracy:
        best_val_accuracy = val_accuracy
        best_model_params = model.state_dict()
        torch.save(best_model_params, model_path)

    # Print statistics
    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {epoch_loss:.4f}, Accuracy: {epoch_accuracy:.4f}, '
          f'Validation Loss: {val_loss:.4f}, Validation Accuracy: {val_accuracy:.4f}')

# Print final results
avg_loss = sum(epoch_losses) / len(epoch_losses)
print(f"Training complete. Average Loss: {avg_loss:.4f}, Best Validation Accuracy: {best_val_accuracy:.4f}")


Epoch [1/1000], Loss: 0.5782, Accuracy: 0.9667, Validation Loss: 0.5593, Validation Accuracy: 1.0000
Epoch [2/1000], Loss: 0.5737, Accuracy: 0.9750, Validation Loss: 0.5611, Validation Accuracy: 1.0000
Epoch [3/1000], Loss: 0.5735, Accuracy: 0.9833, Validation Loss: 0.5636, Validation Accuracy: 1.0000
Epoch [4/1000], Loss: 0.5732, Accuracy: 0.9750, Validation Loss: 0.5633, Validation Accuracy: 1.0000
Epoch [5/1000], Loss: 0.5770, Accuracy: 0.9667, Validation Loss: 0.5629, Validation Accuracy: 1.0000
Epoch [6/1000], Loss: 0.5816, Accuracy: 0.9667, Validation Loss: 0.5619, Validation Accuracy: 1.0000
Epoch [7/1000], Loss: 0.5731, Accuracy: 0.9833, Validation Loss: 0.5609, Validation Accuracy: 1.0000
Epoch [8/1000], Loss: 0.5731, Accuracy: 0.9833, Validation Loss: 0.5602, Validation Accuracy: 1.0000
Epoch [9/1000], Loss: 0.5730, Accuracy: 0.9833, Validation Loss: 0.5598, Validation Accuracy: 1.0000
Epoch [10/1000], Loss: 0.5819, Accuracy: 0.9750, Validation Loss: 0.5603, Validation Accura

In [45]:
import torch
import numpy as np

# Make sure you are accessing a valid index in the dataset
# Let's test the first 10 samples in the dataset (valid indices are from 0 to 149)
for i in range(10):  # Loop through the first 10 samples
    # Extract the features of the i-th sample (change index to be within range)
    dtest = X[i, 0:4]  # Iris dataset has 4 features (indices 0 to 3)
    dtest = np.expand_dims(dtest, axis=0)  # Add batch dimension

    # Convert dtest to a torch tensor and float type
    dtest_tensor = torch.tensor(dtest, dtype=torch.float32)

    # Set the model to evaluation mode
    model.eval()

    # Get predictions
    with torch.no_grad():
        predictions = model(dtest_tensor)

    # Since you're dealing with multi-class classification, you don't need sigmoid. Use softmax.
    # Get the predicted class (the class with the highest probability)
    probabilities = predictions.squeeze().numpy()  # Convert to numpy array
    predicted_class_idx = np.argmax(probabilities)  # Get the index of the max probability
    predicted_class_name = ["Setosa", "Versicolor", "Virginica"][predicted_class_idx]

    # Output probabilities for each class
    print(f"Sample {i+1}:")
    print(f"Predicted Class: {predicted_class_name} (Class {predicted_class_idx})")
    print(f"Class Probabilities: Setosa: {100*probabilities[0]:.2f}%, Versicolor: {100*probabilities[1]:.2f}%, Virginica: {100*probabilities[2]:.2f}%")
    print("-" * 50)

Sample 1:
Predicted Class: Setosa (Class 0)
Class Probabilities: Setosa: 100.00%, Versicolor: 0.00%, Virginica: 0.00%
--------------------------------------------------
Sample 2:
Predicted Class: Setosa (Class 0)
Class Probabilities: Setosa: 100.00%, Versicolor: 0.00%, Virginica: 0.00%
--------------------------------------------------
Sample 3:
Predicted Class: Setosa (Class 0)
Class Probabilities: Setosa: 100.00%, Versicolor: 0.00%, Virginica: 0.00%
--------------------------------------------------
Sample 4:
Predicted Class: Setosa (Class 0)
Class Probabilities: Setosa: 100.00%, Versicolor: 0.00%, Virginica: 0.00%
--------------------------------------------------
Sample 5:
Predicted Class: Setosa (Class 0)
Class Probabilities: Setosa: 100.00%, Versicolor: 0.00%, Virginica: 0.00%
--------------------------------------------------
Sample 6:
Predicted Class: Setosa (Class 0)
Class Probabilities: Setosa: 100.00%, Versicolor: 0.00%, Virginica: 0.00%
-------------------------------------

In [36]:
# model is your variable that you have trained to save in model folder

## Answer Here ##
torch.save(model.state_dict(), model_path)

time: 6.39 ms (started: 2025-07-08 07:41:49 +00:00)


In [46]:
import torch
import numpy as np

# Assuming 'model' is your trained model and 'X' is your dataset
# Use a valid index (0 to 149)
dtest = X[50, 0:4]  # Iris dataset has 4 features (Sepal length, Sepal width, Petal length, Petal width)
dtest = np.expand_dims(dtest, axis=0)  # Add batch dimension (shape becomes (1, 4))

# Convert dtest to a torch tensor and float type
dtest_tensor = torch.tensor(dtest, dtype=torch.float32)

# Set the model to evaluation mode
model.eval()

# Get predictions
with torch.no_grad():
    predictions = model(dtest_tensor)

# Apply softmax to get probabilities for each class
probabilities = torch.softmax(predictions, dim=1).squeeze().numpy()  # Get class probabilities

# Get the predicted class (the class with the highest probability)
predicted_class_idx = np.argmax(probabilities)  # Index of the class with the highest probability
class_names = ["Setosa", "Versicolor", "Virginica"]  # Class labels for Iris dataset
predicted_class = class_names[predicted_class_idx]

# Print the result
print(f"Probabilities for each class:")
for i, class_name in enumerate(class_names):
    print(f"{class_name}: {100 * probabilities[i]:.2f}%")

print(f"\nThe predicted class is: {predicted_class} (Class {predicted_class_idx})")

Probabilities for each class:
Setosa: 21.19%
Versicolor: 57.61%
Virginica: 21.19%

The predicted class is: Versicolor (Class 1)
time: 6.78 ms (started: 2025-07-08 07:52:19 +00:00)
